#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iCycle.Database
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="iCycle")]
	public partial class WeeklySummaryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertWeeklyZoneSummary(WeeklyZoneSummary instance);
    partial void UpdateWeeklyZoneSummary(WeeklyZoneSummary instance);
    partial void DeleteWeeklyZoneSummary(WeeklyZoneSummary instance);
    #endregion
		
		public WeeklySummaryDataContext() : 
				base(global::iCycle.Properties.Settings.Default.iCycleConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public WeeklySummaryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WeeklySummaryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WeeklySummaryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public WeeklySummaryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<WeeklyZoneSummary> WeeklyZoneSummaries
		{
			get
			{
				return this.GetTable<WeeklyZoneSummary>();
			}
		}
	}
	
	[Table(Name="dbo.WeeklyZoneSummary")]
	public partial class WeeklyZoneSummary : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _DurationLightZone;
		
		private string _DurationModerateZone;
		
		private string _DurationHardZone;
		
		private int _Id;
		
		private System.DateTime _WeekStartDate;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDurationLightZoneChanging(string value);
    partial void OnDurationLightZoneChanged();
    partial void OnDurationModerateZoneChanging(string value);
    partial void OnDurationModerateZoneChanged();
    partial void OnDurationHardZoneChanging(string value);
    partial void OnDurationHardZoneChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnWeekStartDateChanging(System.DateTime value);
    partial void OnWeekStartDateChanged();
    #endregion
		
		public WeeklyZoneSummary()
		{
			OnCreated();
		}
		
		[Column(Storage="_DurationLightZone", DbType="VarChar(50)")]
		public string DurationLightZone
		{
			get
			{
				return this._DurationLightZone;
			}
			set
			{
				if ((this._DurationLightZone != value))
				{
					this.OnDurationLightZoneChanging(value);
					this.SendPropertyChanging();
					this._DurationLightZone = value;
					this.SendPropertyChanged("DurationLightZone");
					this.OnDurationLightZoneChanged();
				}
			}
		}
		
		[Column(Storage="_DurationModerateZone", DbType="VarChar(50)")]
		public string DurationModerateZone
		{
			get
			{
				return this._DurationModerateZone;
			}
			set
			{
				if ((this._DurationModerateZone != value))
				{
					this.OnDurationModerateZoneChanging(value);
					this.SendPropertyChanging();
					this._DurationModerateZone = value;
					this.SendPropertyChanged("DurationModerateZone");
					this.OnDurationModerateZoneChanged();
				}
			}
		}
		
		[Column(Storage="_DurationHardZone", DbType="VarChar(50)")]
		public string DurationHardZone
		{
			get
			{
				return this._DurationHardZone;
			}
			set
			{
				if ((this._DurationHardZone != value))
				{
					this.OnDurationHardZoneChanging(value);
					this.SendPropertyChanging();
					this._DurationHardZone = value;
					this.SendPropertyChanged("DurationHardZone");
					this.OnDurationHardZoneChanged();
				}
			}
		}
		
		[Column(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[Column(Storage="_WeekStartDate", DbType="DateTime NOT NULL")]
		public System.DateTime WeekStartDate
		{
			get
			{
				return this._WeekStartDate;
			}
			set
			{
				if ((this._WeekStartDate != value))
				{
					this.OnWeekStartDateChanging(value);
					this.SendPropertyChanging();
					this._WeekStartDate = value;
					this.SendPropertyChanged("WeekStartDate");
					this.OnWeekStartDateChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
